### ISSUE TITLE
[Bug] self literal issue

### ISSUE THREAD

**Issue by dtitov** [dmytrostriletskyi/accessify#25]
This lib becomes quite fragile when it comes to `self` literal. Check out the example below (which is a slightly modified example from the readme):

```
from accessify import private


class Car:

    @private
    def start_engine(self):
        return 'Engine sound.'

    def run(self):
        return self.start_engine()


class Hooman:

    def drive(another_self):
        self = Car()

        assert 'Engine sound.' == self.run()

        print(self.start_engine())


if __name__ == '__main__':
    hooman = Hooman()
    hooman.drive()

```

When you execute this code you will not get any exceptions. I assume this happens because `Car()` object is assigned to a variable called `self`. Which brings me to an idea that this is not how it should be implemented:
```
class ClassMemberDefaultArguments:
    """
    Provide class members arguments default values.
    """

    SELF = 'self'
    CLS = 'cls'
```

Otherwise, you are just relying on another Python convention (about the usage of the `self` literal), which you tried to avoid in the first place.

**Comment by dmytrostriletskyi** [comment]
Hello @dtitov. Appreciate your attention on the library. Please, take a look at the following pull request — https://github.com/dmytrostriletskyi/accessify/pull/26. This pull request contains the fixes that allow passing any instance reference name (i.e. `this`) as the first argument of the instance method, stop being dependent on the `self` literal.

Now, the code in the pull request is a bit ugly, undocumented, and works only for `private accessibility level`, but:
- tests [are provided](https://github.com/dmytrostriletskyi/accessify/blob/a8bd70385901300b73f748892ccb1861b3d11250/tests/access/test_private_class_is_caller.py),
- tests [are passed](https://travis-ci.com/dmytrostriletskyi/accessify/jobs/186522430#L653) on the continuous integration.

Could you please verify I completely covered the issue? Then I will fix `protected accessibility level`.

**Comment by dmytrostriletskyi** [comment]
Closed due to https://github.com/dmytrostriletskyi/accessify/pull/26#issuecomment-476874710.
